mongo:
  image:
    repository: mongo
    tag: "8"
  service:
    port: 27017

chat-backend:
  image:
    repository: ebadarshad/chat-backend
    tag: "latest"
  service:
    port: 3000

chat-frontend:
  image:
    repository: ebadarshad/chat-frontend
    tag: "latest"
  service:
    port: 80
    targetPort: 80