mongo:
  image:
    repository: mongo
    tag: "8"
  replicaCount: 1
  service:
    port: 27017
chat-backend:
  image:
    repository: ebadarshad/chat-backend
    tag: "0.17"
  replicaCount: 2
  revisionHistoryLimit: 1
  service:
    port: 3000
chat-frontend:
  image:
    repository: ebadarshad/chat-frontend
    tag: "0.17"
  replicaCount: 2
  revisionHistoryLimit: 1
  service:
    port: 80
    targetPort: 80
