apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.arcjet }}
  labels: {{- include "chat-backend.labels" . | nindent 4 }}
type: Opaque
data:
  arcjet-key: YWprZXlfMDFrOHYwenF4cmYzMGJxNDZwMjA1bXA1YTkK
  arcjet-development: ZGV2ZWxvcG1lbnQK