apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.cloudinary }}
  labels: {{- include "chat-backend.labels" . | nindent 4 }}
type: Opaque
data:
  cloudinary-name: ZG93ZnVzc2oxCg==
  cloudinary-api-key: OTI1MjIzMjcyNTIxNjc5Cg==
  cloudinary-api-secret: Z3I0Z09FWE4xMWpFWjFWWU5mN0JNLTVWRjVrCg==
