apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.database }}
  labels: {{- include "chat-backend.labels" . | nindent 4 }}
type: Opaque
data:
  url: bW9uZ29kYjovL3Jvb3Q6cGFzc3dvcmRAbW9uZ286MjcwMTcvY2hhdD9hdXRoU291cmNlPWFkbWluCg==
