apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chat-backend.fullname" . }}
  labels:
    {{- include "chat-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chat-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chat-backend.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          -  containerPort: {{ .Values.service.port }}
          
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.livenessProbe.tcpSocket.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}

          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.readinessProbe.tcpSocket.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}

          env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: {{ .Values.auth.database }}
                key: url

          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.auth.jwt }}
                key: jwt-secret

          - name: RESEND_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.auth.resend }}
                key: resend-api-key

          - name: CLOUDINARY_CLOUD_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.auth.cloudinary }}
                key: cloudinary-name
          - name: CLOUDINARY_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.auth.cloudinary }}
                key: cloudinary-api-key
          - name: CLOUDINARY_API_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.auth.cloudinary }}
                key: cloudinary-api-secret

          - name: ARCJET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.auth.arcjet }}
                key: arcjet-key
          - name: ARCJET_ENV
            valueFrom:
              secretKeyRef:
                name: {{ .Values.auth.arcjet }}
                key: arcjet-development
