apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.jwt }}
  labels: {{- include "chat-backend.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: dExadTg5TGRNR0ttd2MzUnFIMWhOY3VZMThJYlUzY2x4cHJ1VEJXUTd4RnJYT0JCU09wdkRBOTQ4VW53NER3dHl2SHE5WkJ0V2ZldERTNE1XT1hVNDkK