apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.resend }}
  labels: {{- include "chat-backend.labels" . | nindent 4 }}
type: Opaque
data:
  resend-api-key: cmVfaXJOWGM1TnhfN3dFWW9lY3h6dFdoU1pFUUZualNneWh5Cg==
