apiVersion: v1
kind: Service
metadata:
  name: {{ include "chat-backend.fullname" . }}
  labels:
    {{- include "chat-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
    
  selector:
    {{- include "chat-backend.selectorLabels" . | nindent 4 }}
