apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mongo.fullname" . }}
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.storage }}
  {{- with .Values.persistentVolume.accessModes }}
  accessModes: 
    {{- toYaml . | nindent 12 }}
  {{- end }}
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.persistentVolumeReclaimPolicy}}
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath.path }}