apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.name }}
  labels: {{- include "mongo.labels" . | nindent 4 }}
type: Opaque
data:
  username: cm9vdA==
  password: cGFzc3dvcmQ=
  db: Y2hhdAo=