apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongo.fullname" . }}
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    {{- include "mongo.selectorLabels" . | nindent 4 }}
