apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chat-frontend.fullname" . }}
  labels:
    {{- include "chat-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chat-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chat-frontend.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            -  containerPort: {{ .Values.service.port }}